### ISSUE TITLE
PB demo app - use file hash in a *.bundle.js name

### ISSUE THREAD

**Issue by sidoruka** [epam/pipeline-builder#33]
Right now demo app, hosted at http://pb.opensource.epam.com, uses JS bundles without any information on changes that occured during rebuilding. (I.e. `main.bundle.js`, `vendor.bundle.js`, etc.).
This causes web-browser cache usage even if changes were made to bundles (e.g. `Build` button added). 
Such behaviour has a workaround to use `CTRL+F5` when loading a demo app, but this does not look as a user-friendly soultion.

It would be nice to configure demo-app build routine to include hashes into bundle names, so that `js` files will be reloaded if they were changed.

**Comment by sidoruka** [comment]
@daniilsavchuk , could you take care of this?

**Comment by daniilsavchuk** [comment]
@sidoruka Yes of course, proposed solution looks good!

**Comment by daniilsavchuk** [comment]
@sidoruka, I enabled the bundle hashing on stand building system. Right now all bundles are hashing and them will be reloaded by browser after every changes applied.

**Comment by sidoruka** [comment]
Nice, closing this issue
