### ISSUE TITLE
Automatic redeploy of a demo application per commit

### ISSUE THREAD

**Issue by sidoruka** [epam/pipeline-builder#4]
Right now, when a `pipeline-builder` sources are updated - demo app (http://pb.opensource.epam.com) should rebuilt and redeployed by hand.
It would be great to update demo app with newest `pipeline-builder` features, once they appear in
- `dev` branch
- `master` branch

(probably that should be different endpoints on a demo server)

**Comment by daniilsavchuk** [comment]
With [PR#17](https://github.com/epam/pipeline-builder/pull/17) autodeploy has configured on dev branch and will appear on master since first merging dev into master

**Comment by daniilsavchuk** [comment]
With PR#17 autodeploy has configured on **dev** branch and will appear on **master** since first merging **dev** into **master** branch. If everything working OK, please @sidoruka could you mark it as resolved

**Comment by sidoruka** [comment]
Nice. Seems that all works fine.
