### ISSUE TITLE
IF Statements parsing

### ISSUE THREAD

**Issue by ainikolaev2013** [epam/pipeline-builder#5]
Hello,
It looks like the IF statements are not parsed correctly during the WDL --> graph action.

The if statement box is drawn as a separate box with a single entry point not connected to anything. The contents of the of the if statement are not parsed at all.

Sincerely,
Alex.

**Comment by sidoruka** [comment]
Hi, Alex, 

Thanks for pointing this out.
This feature was not supported till today. PR https://github.com/epam/pipeline-builder/pull/3 introduced the support for:
* IF
* Loops
* Scather/Gather

It is already merged into `dev` branch and soon will be available on a [DEMO site](http://pb.opensource.epam.com).
I will let you know when it will be ready to test.

**Comment by ainikolaev2013** [comment]
Sounds great, awesome!

**Comment by ainikolaev2013** [comment]
@sidoruka , did you guys have a chance to update the master branch?

**Comment by sidoruka** [comment]
@ainikolaev2013 , sorry for the delay. 
All required changes are merged into `dev` branch (a default one), also these features are already available via a [demo site](http://pb.opensource.epam.com/)

We shall perform some more QA prior to merging into `master`, but feature is already usable to play with

**Comment by nikolaevbroad** [comment]
Awesome, thank you very much!
Any idea on when it could be added to `master`?

**Comment by sidoruka** [comment]
`dev` is merged into `master`.
NPM package is published too.

Please let us know if latest features fit your needs.

**Comment by nikolaevbroad** [comment]
@sidoruka , let me test them out and I will get back to you.
Thanks!

**Comment by sidoruka** [comment]
Seems this issues is a bit outdated.
Closing it in favour of #36 and other `if` and `scatter` related issues
